### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by lvanness7690** [lvanness7690/cinematic-compass#4]

**Comment by biancamistretta** [comment]
Cinematic Compass: A tool to search for TV shows and create a list of shows the user wants to watch. The site will open with a search bar to search for shows. There will also be a button to show ten shows based on popularity under the search bar. On the right side of the list of shows is an "Add to schedule" button where the user can add the show to their schedule list. On the bottom of the page, there is a "Schedule" button which brings the user to the list they've created. This list will show the information about the TV show chosen. This site will allow the user to search for shows and create a list of what they'd like to watch based on their search.
